#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# v1.0 - initial release:
# Author: Davide Del Grande <davide.delgrande _ lanewan.it> / <delgrande.davide _ gmail.com>
# Based on original apc_inrow_* plugin in Check_MK 1.2.8p13
# This plugin supports APC InRow Gen2 RD, which has different OIDs
# http://www.oidview.com/mibs/318/PowerNet-MIB.html
# v1.1 - update for check_mk 2.x
# Author: Adrian Noss <dadrian.noss@gmail.com>


def inventory_apc_inrowg2rd_fanspeed(info):
    if info:
        return [ (None, None) ]

def check_apc_inrowg2rd_fanspeed(_no_item, _no_params, info):
    value = savefloat(info[0][0]) / 10
    return 0, "%.2f%%" % value, [ ("fanspeed", value ) ]

check_info["apc_inrowg2rd_fanspeed"] = {
    "check_function"        : check_apc_inrowg2rd_fanspeed,
    "inventory_function"    : inventory_apc_inrowg2rd_fanspeed,
    "service_description"   : "Evaporator Fanspeed",
    "snmp_info"             : ( ".1.3.6.1.4.1.318.1.1.13.4.5.2.1", [ "22" ] ),
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.318.1.3.14.8"),
    "has_perfdata"          : True,
}
